name: GitVersioning
on:
  workflow_call:
    outputs:
      package_version:
        description: "Package version"
        value: ${{ jobs.versioning-output.outputs.package_version }}

jobs:
  versioning-output:
    runs-on: ubuntu-latest
    name: GitVersion
    outputs:
      package_version: ${{ steps.gitversion.outputs.fullSemVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.12.0"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true
          configFilePath: "GitVersion.yml"
      - run: |
          echo "fullSemVer="`echo ${{ steps.gitversion.outputs.fullSemVer }}` >> $GITHUB_OUTPUT
          echo "Package version: ${{ steps.gitversion.outputs.fullSemVer}} " >> GITHUB_STEP_SUMMARY